### ISSUE TITLE
Restarted GMRES did not converge

### ISSUE THREAD

**Issue by khorrami1** [RJDennis/NLboxsolve.jl#17]
Hi,

I am using NLboxsolve to solve my nonlinear system equations through JFNK:
sol = nlboxsolve(f, x, xtol=1e-6, ftol=1e-6, maxiters=10, method=:jfnk, sparsejac=:yes,krylovdim=50)

, but I got the error message: "ERROR: Restarted GMRES did not converge". My question is how I can change the arguments of GMRES, e.g. tolerance and maximum iterations.

As a suggestion, it would be great to add show_trace in this package to see what happens during iterations.

Thank you in advance,
Mohammad

**Comment by RJDennis** [comment]
Adding a show_trace is a good idea.  Were you able to get your problem to solve using any of the other solvers?  Also, does changing the value for krylovdim help?  At the moment I don't have a nice way for the user to access the arguments of GMRES from the nlboxsolve function.  Maybe I need to add a separate function just for the Newton Krylov methods that exposes those options.

**Comment by RJDennis** [comment]
I've added a solver trace to the solution results in version 0.3.4.

**Comment by khorrami1** [comment]
Many thanks for the update.

**Comment by khorrami1** [comment]
> Adding a show_trace is a good idea. Were you able to get your problem to solve using any of the other solvers? Also, does changing the value for krylovdim help? At the moment I don't have a nice way for the user to access the arguments of GMRES from the nlboxsolve function. Maybe I need to add a separate function just for the Newton Krylov methods that exposes those options.

I think my problem has issue.
